meta:
  url: htttps://powershell.surge.sh
  title: PowerShell is Awesome
  description: Share the greatness of PowerShell
  siteName: PowerShell is Awesome
  sns: ['twitter']
slide:
  loop: false
  ui:
    sidebar: true
    pagination: bullets
    targetBlank: true
  code:
    languages:
      - markdown
      - powershell
    plugins: []
    theme: tomorrow
build:
  useCache: false
extends:
  js: prism.js